version: '3'

services:
  web:
    build: .
    ports:
    - "5000:5000"
    links:
    - postgres
  postgres:
    image: "postgres:9.6"
    environment:
       POSTGRES_USER: hs3city
       POSTGRES_PASSWORD: hs3city

